<?php

namespace AppBundle\Repository;

/**
 * LaundryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaundryRepository extends \Doctrine\ORM\EntityRepository
{
}
