<?php

namespace AppBundle\Repository;

/**
 * MachineTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
