app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
machines:
    resource: "@AppBundle/Controller/Api/MachineController.php"
    type: rest
