app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
#machines:
#    type: rest
#    resource: AppBundle\MachineController
